---
# Create or update a Source connector
- name: Perform a PUT to create or update a Source Connector
  ansible.builtin.uri:
    url: http://localhost:8083/connectors/mariadb_source/config
    method: PUT
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ lookup('template', 'source.json.j2') }}"
    status_code:
      - 200
      - 201

# Create or update a Sink connector
- name: Perform a PUT to create or update a Sink Connector
  ansible.builtin.uri:
    url: http://localhost:8083/connectors/tidb_sink/config
    method: PUT
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ lookup('template', 'sink.json.j2') }}"
    status_code:
      - 200
      - 201