---
- name: Ansible playbook to configure ProxySQL and Debezium

  gather_facts: false

  become: true

  hosts:
    - debezium

  # allowing logs to be printed on the console can expose sensitive information
  # when deploying to production via CI/CD
  no_log: false

  vars_files:
    - vars/main.yml

  roles:
    - debezium # for kafka-connect / debezium connectors
    #- proxysql # proxysql for managing connections and traffic