---
- name: Ansible playbook to configure ProxySQL and Debezium

  gather_facts: false

  become: true

  hosts:
    - debezium

  # allowing logs to be printed on the console can expose sensitive information
  # when deploying to production via CI/CD
  no_log: false

  vars_files:
    - vars/main.yml

  roles:
    - rds # to create a database user in the rds instance
    - tidb # to create a database user in the tidb instance
    - debezium # to create kafka-connect / debezium source and sink connectors
    - proxysql # to configure proxysql to write to the RDS and read from tidb