---
- name: Add ProxySQL backend servers
  proxysql_backend_servers:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    hostname: "{{ item.hostname }}"
    hostgroup_id: "{{ item.hostgroup_id }}"
    max_connections: "{{ item.max_connections | default('100') }}"
    max_replication_lag: "{{ item.max_replication_lag | default('60') }}"
    weight: "{{ item.weight | default('1') }}"
    compression: "0"
    state: present
    port: "{{ item.port | default('3306') }}"
    use_ssl: "{{ item.use_ssl | default('0') }}"
    load_to_runtime: true
    save_to_disk: true
  with_items:
    - {
        hostname: "{{ database_host }}",
        hostgroup_id: "1",
        port: "3306",
        use_ssl: "0",
        comment: "Write hostgroup",
      }
    - {
        hostname: "{{ tidb_host }}",
        hostgroup_id: "2",
        port: "4000",
        use_ssl: "1",
        comment: "Read hostgroup",
      }
