---
- name: Add ProxySQL Users
  proxysql_mysql_users:
    login_user: "admin"
    login_password: "{{ proxysql_admin_password }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    default_hostgroup: "{{ item.default_hostgroup }}"
    max_connections: "{{ item.max_connections | default('100') }}"
    state: present
    active: true
    load_to_runtime: true
    save_to_disk: true
  with_items:
    - {
        username: "{{ database_username }}",
        password: "{{ database_password }}",
        default_hostgroup: "1",
      }
    - {
        username: "{{ tidb_username }}",
        password: "{{ tidb_password }}",
        default_hostgroup: "2",
      }